### ISSUE TITLE
Code2Vec: Dataloader

### ISSUE THREAD

**Issue by juergendkeba** [fetchai/ledger#893]
- [x]  Implement a dataloader for running the code2vec pipeline (c.f. the existing dataloader in the ml library)
  - [x] Reading files in c2v format (i.e. " func_name contexts contexts contexts \n func_name ... ")
  - [x] Counting functions, words and paths
  - [x] Hashing functions, words, paths
  - [x] GetNext(), Size(), ... methods
- [ ] Cross-check how the batching works in the python implementation (https://github.com/tech-srl/code2vec#additional-datasets) 

c.f. the 7L-fork: https://github.com/7lytix/fetch-ledger/tree/code2vec_dataloader
